# Generated by Django 3.2 on 2022-01-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_indipagecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='appDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='Restore', max_length=1000)),
                ('document4', models.FileField(blank=True, upload_to='Documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
