# Generated by Django 3.2 on 2022-01-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_appdocuments_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Document', max_length=1000)),
                ('image', models.ImageField(upload_to='Advertisements/images/')),
                ('pageContent', models.TextField()),
                ('document4', models.FileField(blank=True, upload_to='Advertisements/Documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schemes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Document', max_length=1000)),
                ('image', models.ImageField(upload_to='Schemes/images/')),
                ('pageContent', models.TextField()),
                ('document4', models.FileField(blank=True, upload_to='Schemes/Documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='appdocuments',
            name='title',
            field=models.CharField(default='Document', max_length=1000),
        ),
    ]
