# Generated by Django 3.2 on 2022-01-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20220116_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerloan',
            name='Que1',
            field=models.CharField(default='Have you taken a loan previously?', max_length=1000),
        ),
        migrations.AlterField(
            model_name='workerloan',
            name='Que2',
            field=models.CharField(default='Do you need loan?', max_length=1000),
        ),
        migrations.AlterField(
            model_name='workerloan',
            name='Que3',
            field=models.CharField(default='Have you filed your ITR for last 3 years?', max_length=1000),
        ),
        migrations.AlterField(
            model_name='workerloan',
            name='Que4',
            field=models.CharField(default='Do you have your CIBIL report?', max_length=1000),
        ),
        migrations.AlterField(
            model_name='workerloan',
            name='Que5',
            field=models.CharField(default='Does your bank send you the bank statement on email?', max_length=1000),
        ),
        migrations.AlterField(
            model_name='workerloan',
            name='Que6',
            field=models.CharField(default='last 1 year turnover?', max_length=1000),
        ),
        migrations.AlterField(
            model_name='workerloan',
            name='Que7',
            field=models.CharField(default='Do you have Udyog Aadhar Shop Act License?', max_length=1000),
        ),
        migrations.AlterField(
            model_name='workerloan',
            name='Que8',
            field=models.CharField(default='Do you live on rent? Do you have a rent agreement?', max_length=1000),
        ),
        migrations.AlterField(
            model_name='workerloan',
            name='Que9',
            field=models.CharField(default='For 1 Lakh Rupees to 25 Lakh Rupees loan, do you have a project report and a training done?', max_length=1000),
        ),
    ]
