# Generated by Django 3.2 on 2022-01-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20220116_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='email',
            field=models.CharField(default=1, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customers',
            name='password',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
