from unicodedata import name
from django.urls import path
from . import views
urlpatterns = [
    path('',views.index,name='index'),
    path('About_Us/',views.About_Us,name='About_Us'),
    path('Regional_List/',views.Regional_List,name='Regional_List'),
    path('Documents/',views.Documents,name='Documents'),
    path('Advertisements/',views.Advertisements,name='Advertisements'),
    path('Advertisements/<id>',views.IndexAdvertisements,name='IndexAdvertisements'),
    path('Schemes/',views.Schemes,name='Schemes'),
    path('Schemes/<id>',views.IndexSchemes,name='IndexSchemes'),
    path('Quick_Links/',views.Quick_Links,name='Quick_Links'),
    path('Gallery/',views.Gallery,name='Gallery'),
    path('Contact_Us/',views.Contact_Us,name='Contact_Us'),
    path('Logins/',views.Logins,name='Logins'),
    path('CustomersReg/',views.CustomersReg,name='CustomersReg'),
    path('WorkerReg/',views.WorkerReg,name='WorkerReg'),
    path("WorkerLoanReg/", views.WorkerLoanReg, name="WorkerLoanReg"),
    path("WorkerLoanReg/WorkerLoanSuccess/<id>", views.WorkerLoanSuccess, name="WorkerLoanSuccess"),
    path("BusinessOwnerReg/", views.BusinessOwnerReg, name="BusinessOwnerReg"),
    path("BusinessOwnerReg/BusinessOwnerRegSuccess/<id>/", views.BusinessOwnerRegSuccess, name="BusinessOwnerRegSuccess"),
    path("DistrictHandlerReg/", views.DistrictHandlerReg, name="DistrictHandlerReg"),
    path("DistrictHandlerReg/DistrictHandlerRegSuccess/<id>", views.DistrictHandlerRegSuccess, name="DistrictHandlerRegSuccess"),
    path("TalukaHandlerReg/", views.TalukaHandlerReg, name="TalukaHandlerReg"),
    path("TalukaHandlerReg/TalukaHandlerRegSuccess/<id>/", views.TalukaHandlerRegSuccess, name="TalukaHandlerRegSuccess"),
    path("OperatorReg/", views.OperatorReg, name="OperatorReg"),
    path("OperatorReg/OperatorRegSuccess/<id>", views.OperatorRegSuccess, name="OperatorRegSuccess"),
    path("WorkerReg/WorkerRegSuccess/<id>/", views.WorkerRegSuccess, name="WorkerRegSuccess"),
    path("CustomersReg/CustomersRegSuccess/<id>/", views.CustomersRegSuccess, name="CustomersRegSuccess"),
    path("CustomersReg/CustomersRegFailure/<email>/", views.CustomersRegFailure, name="CustomersRegFailure"),
    path('login/', views.View_Login, name="LoginPath"),
    path('LogOut/', views.LogOut, name="LogOut"),
    path('profile/', views.profile, name="profile"),
    path('WorkersView/', views.WorkersView, name="WorkersView"),
]
